In [6]:
import pandas as pd
import numpy as np
import sklearn
df = pd.read_csv("mymoviedb.csv", engine="python")

In [265]:
df = df[["Title", "Overview", "Genre", "Poster_Url"]]

In [266]:
df.head()

,Title,Overview,Genre,Poster_Url
0,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,The Batman,"In his second year of fighting crime, Batman u...","Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,No Exit,Stranded at a rest stop in the mountains durin...,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,Encanto,"The tale of an extraordinary family, the Madri...","Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,The King's Man,As a collection of history's worst tyrants and...,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [267]:
df.isna().sum()

Title          9
Overview       9
Genre         11
Poster_Url    11
dtype: int64

In [269]:
df.dropna(inplace=True)

In [270]:
df.reset_index(drop=True, inplace=True)

In [271]:
df

,Title,Overview,Genre,Poster_Url
0,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,The Batman,"In his second year of fighting crime, Batman u...","Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,No Exit,Stranded at a rest stop in the mountains durin...,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,Encanto,"The tale of an extraordinary family, the Madri...","Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,The King's Man,As a collection of history's worst tyrants and...,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...
...,...,...,...,...
9821,Badlands,A dramatization of the Starkweather-Fugate kil...,"Drama, Crime",https://image.tmdb.org/t/p/original/z81rBzHNgi...
9822,Violent Delights,A female vampire falls in love with a man she ...,Horror,https://image.tmdb.org/t/p/original/4b6HY7rud6...
9823,The Offering,When young and successful reporter Jamie finds...,"Mystery, Thriller, Horror",https://image.tmdb.org/t/p/original/h4uMM1wOhz...
9824,The United States vs. Billie Holiday,Billie Holiday spent much of her career being ...,"Music, Drama, History",https://image.tmdb.org/t/p/original/vEzkxuE2sJ...
9825,Threads,Documentary style account of a nuclear holocau...,"War, Drama, Science Fiction",https://image.tmdb.org/t/p/original/lBhU4U9Eeh...

In [272]:
df["Genre"] = df["Genre"].str.replace(" ","")

In [273]:
df["Overview"] = df["Overview"].str.split()

In [274]:
df["Genre"] = df["Genre"].str.replace(","," ").str.split()

In [275]:
df["tag"] = df["Overview"] + df["Genre"]

In [276]:
df["tag"].values

array([list(['Peter', 'Parker', 'is', 'unmasked', 'and', 'no', 'longer', 'able', 'to', 'separate', 'his', 'normal', 'life', 'from', 'the', 'high-stakes', 'of', 'being', 'a', 'super-hero.', 'When', 'he', 'asks', 'for', 'help', 'from', 'Doctor', 'Strange', 'the', 'stakes', 'become', 'even', 'more', 'dangerous,', 'forcing', 'him', 'to', 'discover', 'what', 'it', 'truly', 'means', 'to', 'be', 'Spider-Man.', 'Action', 'Adventure', 'ScienceFiction']),
       list(['In', 'his', 'second', 'year', 'of', 'fighting', 'crime,', 'Batman', 'uncovers', 'corruption', 'in', 'Gotham', 'City', 'that', 'connects', 'to', 'his', 'own', 'family', 'while', 'facing', 'a', 'serial', 'killer', 'known', 'as', 'the', 'Riddler.', 'Crime', 'Mystery', 'Thriller']),
       list(['Stranded', 'at', 'a', 'rest', 'stop', 'in', 'the', 'mountains', 'during', 'a', 'blizzard,', 'a', 'recovering', 'addict', 'discovers', 'a', 'kidnapped', 'child', 'hidden', 'in', 'a', 'car', 'belonging', 'to', 'one', 'of', 'the', 'people', 'inside', 'the', 'building', 'which', 'sets', 'her', 'on', 'a', 'terrifying', 'struggle', 'to', 'identify', 'who', 'among', 'them', 'is', 'the', 'kidnapper.', 'Thriller']),
       ...,
       list(['When', 'young', 'and', 'successful', 'reporter', 'Jamie', 'finds', 'out', 'that', 'her', 'sister', 'has', 'died', 'in', 'mysterious', 'circumstances,', 'she', 'travels', 'to', 'Singapore', 'to', 'uncover', 'the', 'truth.', 'There,', 'she', 'discovers', 'multiple', 'deaths', 'linked', 'to', 'her', "sister's", 'and', 'must', 'join', 'forces', 'with', 'her', "sister's", 'husband', 'in', 'order', 'to', 'defeat', 'a', 'demonic', 'entity', 'that', 'is', 'using', 'new', 'technology', 'to', 'complete', 'an', 'ancient', 'mission.', 'Mystery', 'Thriller', 'Horror']),
       list(['Billie', 'Holiday', 'spent', 'much', 'of', 'her', 'career', 'being', 'adored', 'by', 'fans.', 'In', 'the', '1940s,', 'the', 'government', 'targeted', 'Holiday', 'in', 'a', 'growing', 'effort', 'to', 'racialize', 'the', 'war', 'on', 'drugs,', 'ultimately', 'aiming', 'to', 'stop', 'her', 'from', 'singing', 'her', 'controversial', 'ballad,', '"Strange', 'Fruit."', 'Music', 'Drama', 'History']),
       list(['Documentary', 'style', 'account', 'of', 'a', 'nuclear', 'holocaust', 'and', 'its', 'effect', 'on', 'the', 'working', 'class', 'city', 'of', 'Sheffield,', 'England;', 'and', 'the', 'eventual', 'long', 'run', 'effects', 'of', 'nuclear', 'war', 'on', 'civilization.', 'War', 'Drama', 'ScienceFiction'])],
      shape=(9826,), dtype=object)

In [277]:
new_df = df[["Title", "tag"]]

In [278]:
new_df

,Title,tag
0,Spider-Man: No Way Home,"[Peter, Parker, is, unmasked, and, no, longer,..."
1,The Batman,"[In, his, second, year, of, fighting, crime,, ..."
2,No Exit,"[Stranded, at, a, rest, stop, in, the, mountai..."
3,Encanto,"[The, tale, of, an, extraordinary, family,, th..."
4,The King's Man,"[As, a, collection, of, history's, worst, tyra..."
...,...,...
9821,Badlands,"[A, dramatization, of, the, Starkweather-Fugat..."
9822,Violent Delights,"[A, female, vampire, falls, in, love, with, a,..."
9823,The Offering,"[When, young, and, successful, reporter, Jamie..."
9824,The United States vs. Billie Holiday,"[Billie, Holiday, spent, much, of, her, career..."
9825,Threads,"[Documentary, style, account, of, a, nuclear, ..."

In [279]:
new_df["tag"] = new_df["tag"].apply(lambda x: " ".join(x))  # Converting list attributes into strings again

C:\Users\AAYUSH NAITHANI\AppData\Local\Temp\ipykernel_12008\2533656423.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tag"] = new_df["tag"].apply(lambda x: " ".join(x))  # Converting list attributes into strings again

In [280]:
new_df["tag"][0]

'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man. Action Adventure ScienceFiction'

In [281]:
new_df["tag"] = new_df["tag"].str.lower() #Lower Case conversion on=f strings

C:\Users\AAYUSH NAITHANI\AppData\Local\Temp\ipykernel_12008\1872978749.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tag"] = new_df["tag"].str.lower() #Lower Case conversion on=f strings

In [282]:
new_df.head()

                     Title                                                tag
0  Spider-Man: No Way Home  peter parker is unmasked and no longer able to...
1               The Batman  in his second year of fighting crime, batman u...
2                  No Exit  stranded at a rest stop in the mountains durin...
3                  Encanto  the tale of an extraordinary family, the madri...
4           The King's Man  as a collection of history's worst tyrants and...

# Stemming : <h4>Deducing the words to its generalized form which prevents repition of words</h4>

In [283]:
# Performing stemming on TAG column

from nltk.stem import PorterStemmer

porter = PorterStemmer()

l = []

for i in new_df["tag"]:
    l.append(porter.stem(i))
new_df["tag"] = l

C:\Users\AAYUSH NAITHANI\AppData\Local\Temp\ipykernel_12008\3681119662.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tag"] = l

In [284]:
new_df.head()

                     Title                                                tag
0  Spider-Man: No Way Home  peter parker is unmasked and no longer able to...
1               The Batman  in his second year of fighting crime, batman u...
2                  No Exit  stranded at a rest stop in the mountains durin...
3                  Encanto  the tale of an extraordinary family, the madri...
4           The King's Man  as a collection of history's worst tyrants and...

In [285]:
new_df

,Title,tag
0,Spider-Man: No Way Home,peter parker is unmasked and no longer able to...
1,The Batman,"in his second year of fighting crime, batman u..."
2,No Exit,stranded at a rest stop in the mountains durin...
3,Encanto,"the tale of an extraordinary family, the madri..."
4,The King's Man,as a collection of history's worst tyrants and...
...,...,...
9821,Badlands,a dramatization of the starkweather-fugate kil...
9822,Violent Delights,a female vampire falls in love with a man she ...
9823,The Offering,when young and successful reporter jamie finds...
9824,The United States vs. Billie Holiday,billie holiday spent much of her career being ...
9825,Threads,documentary style account of a nuclear holocau...

In [286]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words=None)

In [287]:
vectors = cv.fit_transform(new_df["tag"]).toarray()

In [288]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [289]:
similarity[1]

array([0.17566515, 1.        , 0.28268571, ..., 0.22407133, 0.23338001,
       0.153393  ], shape=(9826,))

In [290]:
def recommend(movie):
    mov_ind = new_df[new_df["Title"]==movie].index[0]
    distances = similarity[mov_ind]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:11]
    for i in movies_list:
        print(new_df.iloc[i[0]].Title)

In [291]:
recommend("Spider-Man: No Way Home")

The Amazing Spider-Man
Psychic Kusuo
Man of Steel
Dracula Untold
Just Before I Go
LEGO DC Comics Super Heroes: Justice League vs. Bizarro League
Avengers: Age of Ultron
Last Moment of Clarity
The Tomorrow War
Tristana

In [292]:
import pickle

pickle.dump(new_df, open("movies.pkl","wb"))

In [293]:
pickle.dump(similarity, open("similarity.pkl", "wb"))

In [294]:
poster = df["Poster_Url"]

In [295]:
poster.head()

0    https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1    https://image.tmdb.org/t/p/original/74xTEgt7R3...
2    https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3    https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4    https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...
Name: Poster_Url, dtype: object

In [296]:
pickle.dump(poster, open("poster.pkl","wb"))

In [3]:
pd.__version__

'2.3.3'

In [4]:
np.__version__

'2.3.5'

In [7]:
sklearn.__version__

'1.9.0'